name: test pipeline
timestamp_format: "%Y-%m-%d %H:%M:%S"
locations:
    source_folder:
        type: directory
        directory_path: /Users/main/Documents/Code/Github/ingestion_framework

    working_folder:
        type: snowflake_landing_zone
        directory_path: /Users/main/Documents/Code/Github/ingestion_framework


steps:
    transport:
        uses: action_one
        params:
            source: source_folder
            target: working_folder
    process:
        depends_on: transport
        uses: action_one
        params:
            source: working_folder
            target: source_folder
            source_file_format: csv
